### ISSUE TITLE
navigation to go back

### ISSUE THREAD

**Issue by devuserPP** [alex-melnyk/flutter_advanced_drawer#10]
Thank you for your work I really like it. But have question. I want use this drawer with "openRatio: 1" and not sure how to go back. Is it possible to implement swipe left for going back like for "original" drawer?

**Comment by alex-melnyk** [comment]
Could you example more what do you expected to see, maybe you can provide some example images

**Comment by devuserPP** [comment]
![swipeLeft](https://user-images.githubusercontent.com/47779720/119101436-46d14280-ba19-11eb-8d38-8acb6121d22d.PNG)

**Comment by alex-melnyk** [comment]
Fixed
