### ISSUE TITLE
Disable gesture for open Drawer

### ISSUE THREAD

**Issue by andrezanna** [alex-melnyk/flutter_advanced_drawer#18]
Hi, 
i'm developing an application and using this plugin.
Since i'm displaying a map i would need to disable the swipe to open Drawer, but couldn't find nothing that works.

`AdvancedDrawer(

        backdropColor: Theme.of(context).primaryColor,
        controller: _advancedDrawerController,
        animationCurve: Curves.easeInOut,
        animationDuration: const Duration(milliseconds: 300),
        childDecoration: const BoxDecoration(
          boxShadow: <BoxShadow>[
            BoxShadow(
              color: Colors.black38,
              blurRadius: 24,
            ),
          ],
          borderRadius: const BorderRadius.all(Radius.circular(16)),
        ),
        drawer: DrawerCustom(),
        child: Scaffold(
          drawerEnableOpenDragGesture: false,
          drawerEdgeDragWidth: 0.0,
          backgroundColor: Colors.white,
          appBar: AppBar(
`
I tried all the options on AdvancedDrawer and to disable this from the Scaffold but no luck.

Is it possible?
Thanks

**Comment by alex-melnyk** [comment]
> I tried all the options on AdvancedDrawer and to disable this from the Scaffold but no luck.
Hi @andrezanna I didn't implement disabling. I'll try to provide this feature.

**Comment by andrezanna** [comment]
Many thanks for your quick reply.
Wonderful, thanks for your work.

**Comment by andrezanna** [comment]
Hello, after a few test i noticed that disableGestures isn't still working perfectly.
Digging up in the code i solved the issue by moving the check on the variable directly in definition

`GestureDetector(
        onHorizontalDragStart: widget.disabledGestures?null:_handleDragStart,
        onHorizontalDragUpdate:widget.disabledGestures?null: _handleDragUpdate,
        onHorizontalDragEnd: widget.disabledGestures?null:_handleDragEnd,
        onHorizontalDragCancel: widget.disabledGestures?null:_handleDragCancel,
        child:`
