### ISSUE TITLE
advenced drawer ne retroune pas la page qui la précède

### ISSUE THREAD

**Issue by Idrissboss** [alex-melnyk/flutter_advanced_drawer#2]
Le problème est rencontré lorsque j'utilise le package (Advenced  drawer ) en combinaison avec n'importe quel nav bar 

Lorsque l'on clique sur le bouton advenced drawer , tout ce passe sans problème, le problème survient lorsque l'on ferme le menu drawer il revient toujours sur la première page (Home)  de la nav bar meme si l'on à ouvert le menu advenced drawer à partir la troisième page de la navbar

**Comment by alex-melnyk** [comment]
Sorry, I don't understand you.
Could you explain your problem in English, please?

**Comment by alex-melnyk** [comment]
Closed due not response.
