### ISSUE TITLE
some times its not opening if i open showGeneralDialog and close it then the drawer is not working

### ISSUE THREAD

**Issue by MohamedKhalid98** [alex-melnyk/flutter_advanced_drawer#24]
some times its not opening if i open showGeneralDialog and close it then the drawer is not working

**Comment by MohamedKhalid98** [comment]
i did some debuging and i saw that this issue come when i focus on TextFormField in that dialog, so i think it's not related to the dialog

**Comment by MohamedKhalid98** [comment]
after some more debugging i discovered that this issue happen when keyboard is shown

**Comment by alex-melnyk** [comment]
So looks like you need to dismiss the keyboard before opening the drawer. If you have suggestions to fix, please provide your code with PR and we can move forward.
