### ISSUE TITLE
home page freezed swiper when use disabledGestures true

### ISSUE THREAD

**Issue by Obada2020** [alex-melnyk/flutter_advanced_drawer#39]

**Comment by alex-melnyk** [comment]
Could you add more details?

**Comment by AALLx** [comment]
Hi @alex-melnyk I encountered the same issue as well. On Flutter 3.3.10, the child object was able to receive tap and drag gestures while the "disabledGestures" parameter is set to true. After updating to Flutter 3.7.1, the child object stopped receiving gestures, and the "disabledGestures" parameter had to be set to false in order for the app to start working again.

**Comment by alex-melnyk** [comment]
> Hi @alex-melnyk I encountered the same issue as well. On Flutter 3.3.10, the child object was able to receive tap and drag gestures while the "disabledGestures" parameter is set to true. After updating to Flutter 3.7.1, the child object stopped receiving gestures, and the "disabledGestures" parameter had to be set to false in order for the app to start working again.

Did you fix that on your end? If yes please create PR

**Comment by Mohammad-Adam** [comment]
I have to disable `HorizontalDrag` to avoid gestures (FOR NOW)

```
@override
  Widget build(BuildContext context) {
    return Material(
      color: widget.backdropColor,
      child: IgnorePointer(
        ignoring: widget.disabledGestures,
        child: GestureDetector(
          // onHorizontalDragStart: _handleDragStart,
          // onHorizontalDragUpdate: _handleDragUpdate,
          // onHorizontalDragEnd: _handleDragEnd,
          // onHorizontalDragCancel: _handleDragCancel,
          child: Container(...),
      ),
    );
  }
````

**Comment by OthmanShaker** [comment]
i confirm, this issue was caused simply by upgrading my flutter to the newest version
