### ISSUE TITLE
Thanks for this awesome library but i feel the animation of the drawer is not smooth i see some jerk when i press hamburger icon

### ISSUE THREAD

**Issue by adnankhan74444** [alex-melnyk/flutter_advanced_drawer#5]

**Comment by alex-melnyk** [comment]
Could you provide more information like:
- `flutter doctor` output
- device name model or emulator configuration
- etc. that might help me to see issue

**Comment by adnankhan74444** [comment]
Iphne x

**Comment by alex-melnyk** [comment]
I’ve requested more information, if could fix that, do PR

**Comment by adnankhan74444** [comment]
https://user-images.githubusercontent.com/33020030/116925428-9e7a5a80-ac72-11eb-884c-ad83a99d5d20.mov

**Comment by adnankhan74444** [comment]
@alex-melnyk  i also checked in release mode animation is not smooth in debug and release mode as you can see in the above video.

**Comment by alex-melnyk** [comment]
https://user-images.githubusercontent.com/30177329/116941219-f1a2dc00-ac77-11eb-9126-8378714d207e.mov

I investigated this issue, mostly it depends on your computer power.
First of all, try it on the real device, keep in mind that the simulator is software that does like a real device.
Also, you can try to manage new props to avoid animation jerks.

**Comment by adnankhan74444** [comment]
@alex-melnyk its working nice in newer version thanks a lot.
