### ISSUE TITLE
When you hot reload the drawer icon doesn't works

### ISSUE THREAD

**Issue by adnankhan74444** [alex-melnyk/flutter_advanced_drawer#6]

**Comment by ArunPrakashG** [comment]
Bump on this issue.

**Comment by alex-melnyk** [comment]
Please provide a PR with fix of this issue

**Comment by adnankhan74444** [comment]
Hi @alex-melnyk can you check this issue from your side ?
Because when ever i do hotreload Drawer icon won't work.

**Comment by MohamedKhalid98** [comment]
some times its not opening if i open showDialogModal and close it then the drawer is not working
